### ISSUE TITLE
PSR-4 errors on install

### ISSUE THREAD

**Issue by weotch** [BKWLD/craft-webhook-scheduler#1]
When I updated Clif to use the [published package](https://packagist.org/packages/bkwld/craft-webhook-scheduler), I got these warnings:

```
Class Bkwld\WebhookScheduler\records\CraftwebhookschedulerRecord located in ./vendor/bkwld/craft-webhook-scheduler/src/records/CraftentriesschedulerRecord.php does not comply with psr-4 autoloading standard. Skipping.
Class Bkwld\WebhookScheduler\models\CraftwebhookschedulerModel located in ./vendor/bkwld/craft-webhook-scheduler/src/models/CraftentriesschedulerModel.php does not comply with psr-4 autoloading standard. Skipping.
```

Looking at https://github.com/BKWLD/craft-webhook-scheduler/blob/master/src/models/CraftentriesschedulerModel.php and https://github.com/BKWLD/craft-webhook-scheduler/blob/master/src/records/CraftentriesschedulerRecord.php, it looks like the class names don't match the filename.

In fixing this, I recommend you switch to more Studly cased class names as well, such as:

- `CraftwebhookschedulerRecord` -> `SchedulerRecord`
- `CraftwebhookschedulerModel` -> `SchedulerModel`

Even better would be a name that is less redundant with the package namespace and more descriptive for what this is a record / model of.

Or maybe these are cruft?  I don't see where they are consumed.

**Comment by isaazgarcia** [comment]
Thanks! I removed those files as we are not using it.
